---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# 👋 Hi, I’m Cavan Donohoe

I am a data scientist working for GRAIL who specializes in R programming. I discovered R programming in 2019 (can you believe that was `r lubridate::year(Sys.Date()) - 2019` years ago??) and have loved it since then. I have a whole project list on my website listed below and a little bit more about me if you'd like to read on.

I'm currently in a phase of my life where I would love to help with some small projects that might need some reproducibility. In this crazy world of high tech AI and incredibly fast computers, why are some people still relying on entire workflows in Excel? It boggles my mind 🤯

R has become a passion of mine and I would love to share that passion with you.

👀 I’m interested in helping people's lives easier.   
🌱 I’m always learning new ways in R to make that achievable.   
📫 Email me at cavandonohoe@gmail.com   

Check out my repositories!

And my website hosted on GitHub Pages: [cavandonohoe.github.io](https://cavandonohoe.github.io/)


